INSERT INTO TB_HORARIO (horario) VALUES ('07:30');
INSERT INTO TB_HORARIO (horario) VALUES ('08:20');
INSERT INTO TB_HORARIO (horario) VALUES ('09:10');
INSERT INTO TB_HORARIO (horario) VALUES ('10:10');
INSERT INTO TB_HORARIO (horario) VALUES ('11:00');
INSERT INTO TB_HORARIO (horario) VALUES ('11:50');

INSERT INTO TB_HORARIO (horario) VALUES ('13:30');
INSERT INTO TB_HORARIO (horario) VALUES ('14:20');
INSERT INTO TB_HORARIO (horario) VALUES ('15:10');
INSERT INTO TB_HORARIO (horario) VALUES ('16:20');
INSERT INTO TB_HORARIO (horario) VALUES ('17:10');
INSERT INTO TB_HORARIO (horario) VALUES ('18:00');

INSERT INTO TB_HORARIO (horario) VALUES ('18:30');
INSERT INTO TB_HORARIO (horario) VALUES ('19:20');
INSERT INTO TB_HORARIO (horario) VALUES ('20:20');
INSERT INTO TB_HORARIO (horario) VALUES ('21:10');
INSERT INTO TB_HORARIO (horario) VALUES ('22:00');

INSERT INTO TB_DIA_SEMANA (nome) VALUES ('Segunda-feira');
INSERT INTO TB_DIA_SEMANA (nome) VALUES ('Terça-feira');
INSERT INTO TB_DIA_SEMANA (nome) VALUES ('Quarta-feira');
INSERT INTO TB_DIA_SEMANA (nome) VALUES ('Quinta-feira');
INSERT INTO TB_DIA_SEMANA (nome) VALUES ('Sexta-feira');
INSERT INTO TB_DIA_SEMANA (nome) VALUES ('Sábado');