fragment Turma on Turma {
  codigo
  vagasOfertadas
  nomeProfessor
  disciplina {
    codigo
    nome
    cargaHoraria
  }
  horarios {
    diaSemana {
      ...DiaSemana
    }
    horario {
      ...Horario
    }
    sala
  }
}
