query BuscarTurmas {
  turmas {
    codigo
    vagasOfertadas
    nomeProfessor
    disciplina {
      codigo
      nome
      cargaHoraria
    }
    horarios {
      diaSemana {
        ...DiaSemana
      }
      horarioInicio {
        ...Horario
      }
      horarioFinal {
        ...Horario
      }
      sala
    }
  }
}
